### ISSUE TITLE
[ui/test] order-replay page calls POST /test/reset on BE to reset test data

### ISSUE THREAD

**Issue by tunggad** [beesEX/ui#15]
Summary:
A link/button on order-replay page, which call POST /test/reset on BE to reset all test data

Prerequisites:
BE task [#28](https://github.com/beesEX/be/issues/28) has to been done first

TODO:
- Place a link/button somewhere on order-replay page with name `reset test data` which calls GET /order-replay/reset per ajax
- a handler function on `controller/order-replay.js` mapped on GET /order-replay/reset calls BE POST /test/reset to reset test data and deposit new fund for the user
- If call to reset on BE is successful, UI client side then calls GET /finance/status/:currency to see new fund deposited for the user, so the user is ready for the next test session.

**Comment by ngocson1** [comment]
closed with commit https://github.com/beesEX/ui/commit/c1f1bed6391cd3513c0df01d59f6f9cbb5a43095
